#!/usr/bin/env python3
"""Per-usecase Voice QR descriptions for injection."""

# Japanese usecase pages: slug -> custom description
DESCRIPTIONS_JA = {
    "airline": "搭乗記念に、機内からの感動や旅の決意を音声で録音。QRコード付き搭乗証明として、空の旅を声と共に永久保存。",
    "architect": "施主の「この家への想い」を声で記録。竣工プレートにQRコードを添えれば、建物と共に想いも残り続けます。",
    "bakery": "パン職人のこだわりや常連客へのメッセージを音声で。店頭POPにQRを添えれば、味だけでなく想いも届きます。",
    "bank": "口座開設の記念に、将来の自分や家族へのメッセージを音声で保存。通帳と共に、声の資産も残せます。",
    "bookstore": "著者サイン会で肉声メッセージ入りQRコードを添付。本と共に作家の声が届く、特別な一冊に。",
    "bowling": "パーフェクトゲームや自己ベスト達成の瞬間を音声で記録。スコアカードにQRを添えて、興奮を永久保存。",
    "butcher": "目利きの技や部位の食べ方を音声で解説。商品パッケージにQRを添えれば、肉屋の知恵が声で届きます。",
    "campsite": "焚き火を囲んだ夜の語らいや自然の音を録音。キャンプの思い出を声ごとQRカードに。",
    "car": "納車の喜びや愛車への想いを音声で記録。オーナーズカードにQRを添えて、最初の感動を永久保存。",
    "cinema": "映画鑑賞後の感想や感動を録音。半券にQRコードを添えれば、あの日の興奮が声で蘇ります。",
    "cleaner": "大切な衣類にまつわるエピソードを音声で記録。クリーニング済みの品に添える、想い出のQRタグ。",
    "concert": "ライブ後の興奮や推しへのメッセージを録音。チケットにQRを添えて、あの夜の感動を永久保存。",
    "corporate": "社員の入社時の抱負や退職時のメッセージを音声で記録。社史と共に、声の歴史も残せます。",
    "crafts": "職人が語る制作秘話や素材へのこだわりを音声で。作品に添えるQRコードで、工芸の魂を伝えます。",
    "cruise": "船上での感動や大海原への想いを音声で記録。乗船記念カードにQRを添えて、航海の記憶を永久保存。",
    "dagashi": "店主の思い出話や駄菓子の由来を音声で。昭和の温もりが声で蘇る、特別なQRカード。",
    "dentist": "治療完了の記念メッセージや、お子様の「頑張った」声を録音。診察券にQRを添えて成長記録に。",
    "diving": "初ダイビングの感動や海中での興奮を水上がり直後に録音。ログブックにQRを添えて、海の記憶を永久保存。",
    "dojo": "昇段試験合格の決意表明や師範の教えを音声で記録。帯や段位証にQRを添えて、武道の志を残します。",
    "electronics": "購入した家電への期待や店員のおすすめポイントを音声で。保証書にQRを添えれば、買い物の記憶も残ります。",
    "farm": "農家が語る土地への想いや栽培のこだわりを音声で。産直品にQRを添えれば、作り手の声が届きます。",
    "fishmonger": "目利きが語る魚の旬や食べ方を音声で。包装にQRを添えれば、魚屋の知恵が声で届きます。",
    "fishing": "大物を釣り上げた興奮や海の思い出を録音。釣果写真にQRを添えて、あの瞬間の声を永久保存。",
    "fitness": "目標達成の喜びやトレーナーからの激励を音声で。会員証にQRを添えて、成長の軌跡を声で残します。",
    "florist": "花言葉や贈り手のメッセージを音声で。花束にQRカードを添えれば、花が枯れても想いは残り続けます。",
    "funeral": "故人の生前の声や家族の弔辞を音声で保存。遺影やメモリアルプレートにQRを添えれば、声が永遠に響きます。",
    "furniture": "家具職人のこだわりや使い手への想いを音声で。納品書にQRを添えれば、暮らしに声の温もりが加わります。",
    "gallery": "アーティスト本人が語る作品への想いを音声で。展示キャプションにQRを添えれば、鑑賞体験が深まります。",
    "garden": "庭師が語る植栽の意図や四季の見どころを音声で。庭園マップにQRを添えて、声のガイドを提供。",
    "general": "お客様の「ありがとう」やスタッフの想いを音声で記録。店舗の歴史と共に、声の記録も残せます。",
    "golf": "ホールインワンの興奮やベストスコアの喜びを録音。スコアカードにQRを添えて、伝説のラウンドを永久保存。",
    "greengrocer": "八百屋が語る旬の野菜の食べ方やこだわりを音声で。買い物袋にQRタグを添えて、食卓に声を届けます。",
    "gym": "自己ベスト更新の瞬間や目標宣言を音声で録音。トレーニング記録にQRを添えて、成長を声で残します。",
    "hardware": "DIYのコツや店員のおすすめを音声で。商品タグにQRを添えれば、プロの知恵が声で届きます。",
    "heritage": "文化財の歴史や保存に携わる人々の想いを音声で。案内板にQRを添えれば、声の解説で歴史が生きます。",
    "horse": "初騎乗の感動や馬との触れ合いを音声で記録。体験証明書にQRを添えて、馬上の風を声と共に。",
    "hospital": "退院時の感謝のメッセージや回復の喜びを音声で記録。診察券にQRを添えて、健康の節目を残します。",
    "hotel": "宿泊の感動や旅の思い出を音声で記録。チェックアウト時にQRカードをお渡しして、滞在の記憶を永久保存。",
    "housing": "新居への想いや家族の決意を音声で記録。引き渡し書類にQRを添えて、マイホームの第一声を永久保存。",
    "instrument": "初めての演奏や購入時の想いを音声で。楽器ケースにQRタグを添えれば、音楽の原点が声で残ります。",
    "insurance": "家族への想いや将来への願いを音声で記録。保険証券にQRを添えて、万が一の時に声で届けます。",
    "izakaya": "常連客との思い出や大将のこだわりを音声で。メニュー表にQRを添えて、味と共に声も楽しめます。",
    "jewelry": "プロポーズの言葉や記念日のメッセージを音声で。ジュエリーボックスにQRを添えて、宝石と共に声も永遠に。",
    "juku": "合格の瞬間の喜びや先生からのエールを音声で。合格証にQRを添えて、努力の記録を声で残します。",
    "karaoke": "十八番の熱唱やグループの盛り上がりを録音。カラオケの思い出をQRカードに封じ込めて。",
    "kindergarten": "園児の歌声やお遊戯会の発表を音声で記録。卒園証書にQRを添えて、成長の声を永久保存。",
    "kissaten": "マスターが語るコーヒーへのこだわりや店の歴史を音声で。コースターにQRを添えて、一杯の物語を。",
    "law": "遺言のメッセージや契約締結時の決意を音声で補完。書類にQRを添えて、声による意思表示も残せます。",
    "lessons": "発表会での演奏や先生からの講評を音声で記録。修了証にQRを添えて、学びの軌跡を声で残します。",
    "library": "読み聞かせの声や著者インタビューを音声で保存。蔵書にQRタグを添えて、声の図書館を実現。",
    "marina": "出航の興奮や海上の風景を声で実況。ログブックにQRを添えて、航海の記憶を永久保存。",
    "moving": "旧居への別れの言葉や新居での抱負を音声で。引越し記念にQRカードとして、人生の節目を声で残します。",
    "municipality": "市民の声や地域の祭りの雰囲気を音声で保存。広報誌にQRを添えて、まちの記憶を声で未来へ届けます。",
    "museum": "学芸員が語る展示品の解説や来館者の感想を音声で。展示パネルにQRを添えて、声の音声ガイドを提供。",
    "npo": "活動に込めた想いや支援者へのメッセージを音声で。報告書にQRを添えて、声で共感を届けます。",
    "nursing": "入居者の人生語りや家族からのメッセージを音声で保存。居室にQRプレートを設置して、声で寄り添います。",
    "onsen": "湯上がりの感想や旅館女将のおもてなしの声を録音。宿泊記念カードにQRを添えて、湯の記憶を永久保存。",
    "optician": "初めてメガネをかけた瞬間の感動を音声で。メガネケースにQRタグを添えて、「世界が変わった」声を残します。",
    "outdoor": "山頂での歓声やキャンプの思い出を音声で記録。体験証にQRを添えて、冒険の記憶を声ごと永久保存。",
    "patisserie": "パティシエのこだわりや特別なケーキに込めた想いを音声で。ギフトボックスにQRを添えて、甘い記憶を声と共に。",
    "pension": "オーナーが語る宿のこだわりや周辺の見どころを音声で。ゲストカードにQRを添えて、声のおもてなしを。",
    "pet": "ペットとの日常や家族としての想いを音声で記録。首輪タグにQRを添えて、共に過ごした日々を永久保存。",
    "petshop": "お迎え初日の喜びやペットへのメッセージを音声で。お迎え証明書にQRを添えて、出会いの声を残します。",
    "pharmacy": "薬剤師からの健康アドバイスやお薬の飲み方を音声で。お薬手帳にQRを添えて、声で健康サポート。",
    "photo": "撮影時の笑い声や家族のやり取りを音声で。写真アルバムにQRを添えれば、写真が声と共に蘇ります。",
    "planetarium": "解説員の星空ガイドや来館者の感動を音声で。観覧チケットにQRを添えて、宇宙への想いを永久保存。",
    "print": "印刷物に音声メッセージ付きQRを追加。名刺、パンフレット、ポスターに「声」という新しい次元を。",
    "publishing": "著者の肉声による作品解説や読者へのメッセージを音声で。書籍の帯やしおりにQRを添えて。",
    "railway": "車窓からの実況や駅のアナウンスを音声で記録。記念きっぷにQRを添えて、鉄道旅の音風景を永久保存。",
    "ramen": "店主が語るスープへのこだわりや常連へのメッセージを音声で。メニュー表にQRを添えて、一杯の哲学を。",
    "renovation": "リフォーム前後の想いや住まいへの愛着を音声で。完工報告書にQRを添えて、暮らしの転機を声で残します。",
    "restaurant": "シェフが語る料理へのこだわりや特別な日の乾杯メッセージを音声で。記念メニューにQRを添えて。",
    "rice": "米農家が語る田んぼの物語やこだわりの品種を音声で。お米の袋にQRタグを添えて、食卓に作り手の声を。",
    "sake": "杜氏が語る酒造りの哲学や蔵の歴史を音声で。酒瓶のラベルにQRを添えれば、一献に物語が加わります。",
    "salon": "施術前後の気持ちやスタイリストからのアドバイスを音声で。スタイルカードにQRを添えて、美の記録を。",
    "school": "卒業生のスピーチや校歌を音声で保存。卒業証書にQRを添えて、青春の声を永久保存。",
    "sento": "常連さんの思い出話や番台さんの声を録音。銭湯の暖簾にQRを添えて、地域の語り場の記憶を残します。",
    "shoe": "初めての革靴やお気に入りの一足への想いを音声で。シューボックスにQRを添えて、一歩の記憶を。",
    "shrine": "参拝の祈りや宮司による御祈祷の言葉を音声で。御朱印帳にQRを添えて、祈りの声を永久保存。",
    "ski": "初滑りの興奮やゲレンデの歓声を音声で記録。リフト券にQRを添えて、雪山の記憶を声ごと永久保存。",
    "spa": "施術後のリラックスした声や感謝のメッセージを録音。トリートメントカードにQRを添えて、癒しの記憶を。",
    "sports": "勝利の瞬間の雄叫びやチームメイトへのメッセージを音声で。メダルや記念品にQRを添えて、栄光を声で残します。",
    "stationery": "お気に入りの万年筆で書いた手紙に音声メッセージを添えて。文具と声で、最高の贈り物を届けます。",
    "stone": "墓石に故人の声や家族のメッセージをQRで添付。石に刻む言葉に加えて、声の記録も半永久的に残せます。",
    "sushi": "大将が握るネタの由来や旬の話を音声で。カウンターにQRを設置して、声のおまかせ解説を提供。",
    "tailor": "仕立ての哲学やお客様への想いを音声で。スーツの内ポケットにQRタグを添えて、一着に物語を。",
    "tatami": "畳職人が語る藺草へのこだわりを音声で。新調した畳にQRプレートを添えて、和の技を声で伝えます。",
    "taxi": "ドライバーが語る街の歴史や隠れスポットを音声で。乗車カードにQRを添えて、声の観光ガイドを提供。",
    "tea": "茶師が語る茶葉の物語や淹れ方のコツを音声で。茶筒にQRタグを添えて、一服に声の深みを。",
    "themepark": "アトラクション体験後の興奮や家族の歓声を録音。パークチケットにQRを添えて、遊園地の思い出を永久保存。",
    "tofu": "豆腐職人が語るにがりの加減や水へのこだわりを音声で。パッケージにQRを添えて、手仕事の声を届けます。",
    "tourbus": "バスガイドの名調子や車窓からの実況を音声で。乗車記念にQRカードをお渡しして、旅の声を永久保存。",
    "tourism": "観光地での感動をその場で録音。QRコード付きカードをお土産として、旅の声を永久保存できます。",
    "toystore": "子どもが語るお気に入りのおもちゃへの想いを音声で。おもちゃの箱にQRを添えて、幼い声を永久保存。",
    "wagashi": "和菓子職人が語る季節の菓子への想いを音声で。化粧箱にQRを添えれば、味と共に声の風情も届きます。",
    "watch": "時計に込めた想いや贈り手のメッセージを音声で。時計ケースにQRを添えて、時を刻む声を永久保存。",
    "wedding": "誓いの言葉や家族からの祝福メッセージを音声で記録。招待状や席札にQRを添えて、声の記念品を。",
    "winery": "醸造家が語るヴィンテージの物語やテロワールを音声で。ワインラベルにQRを添えて、一本に声の深みを。",
    "yoga": "インストラクターの誘導瞑想やクラスの感想を音声で。修了証にQRを添えて、心身の変化を声で残します。",
    "zoo": "飼育員が語る動物たちの個性や裏話を音声で。園内マップにQRを添えて、声の動物ガイドを提供。",
}

# English usecase pages: slug -> custom description
DESCRIPTIONS_EN = {
    "resort": "Record guests' vacation highlights in their own voice at checkout. Hand them a printed QR card — a one-of-a-kind keepsake that replays their paradise memories forever.",
    "boutique-hotel": "Capture guests' personal stories during their stay. A voice-embedded QR card at departure turns intimate hotel experiences into permanent mementos.",
    "vacation-rental": "Let guests record a voice message about their favorite moment. Include a QR keepsake card in premium welcome packages for five-star review impact.",
    "cruise": "Passengers record memories at sea — the sunset, the port of call, the celebration. A QR card preserves voyage moments that play back with no internet needed.",
    "helicopter": "Right after landing, capture passengers' adrenaline-filled reactions. Print a QR card with their flight details — a souvenir that replays the thrill forever.",
    "scenic-flight": "Record passengers' first reactions after seeing Hawaii from above. A voice QR card paired with flight coordinates becomes the ultimate aerial memento.",
    "yacht": "Capture toasts, celebrations, and ocean stories on board. A voice QR card printed at the marina preserves the magic of time at sea.",
    "fishing": "Record the excitement of landing a big catch — the shout, the story, the pride. A QR card with catch details and the angler's voice makes the tale permanent.",
    "whale": "After an encounter, record passengers' awe in their own words. A voice QR card paired with sighting data preserves that magical whale moment.",
    "diving": "Back on the surface, divers record their underwater experience while it's fresh. A QR card on the dive log makes every dive permanently replayable.",
    "snorkel": "Kids' first turtle sighting, a family's reef discovery — record the excitement right after. A voice QR card becomes a family treasure from the ocean.",
    "surf-shop": "Capture a surfer's first wave story or session recap. Print a QR card with spot name and conditions — the surf memory that never fades.",
    "surf-school": "Record students' reactions after standing up for the first time. A voice QR graduation card celebrates their achievement with their own voice.",
    "sup": "After a sunrise paddle, record the serenity in your own voice. A QR keepsake card with GPS route makes the peaceful moment permanent.",
    "golf": "Record the celebration after a hole-in-one or personal best. A voice QR card with scorecard details immortalizes the legendary round.",
    "luau": "Capture family reactions to the fire dance, the hula, the feast. A voice QR card from the evening preserves the aloha spirit in every guest's voice.",
    "zipline": "Record the scream, the laugh, the triumph right after the last line. A voice QR card becomes proof of courage that replays the adrenaline.",
    "hiking": "At the summit, record the panoramic description in your own words. A QR card with trail data and your voice preserves the achievement forever.",
    "horseback": "Capture riders' sunset trail stories right after dismounting. A voice QR card with the horse's name and trail route makes the ride unforgettable.",
    "atv": "Record the mud-splattered, grinning post-ride recap. A voice QR card with trail difficulty and location preserves the off-road adventure forever.",
    "wedding-venue": "Record the vows, the first toast, family blessings. A voice QR card elegantly preserves wedding voices alongside the quartz glass memory.",
    "wedding-planner": "Offer couples a voice QR card capturing their vows or a personal message. A unique add-on to planning packages that no competitor offers.",
    "chapel": "Preserve the officiant's blessing and the couple's vows in audio. A voice QR card adds sacred sound to the sacred visual record.",
    "beach-wedding": "Capture barefoot vows with the sound of waves in the background. A voice QR card becomes the most intimate keepsake of the ceremony.",
    "wedding-photo": "Pair your signature shot in quartz with the couple's spoken vows on a QR card. Two senses, one eternal memory package.",
    "bridal-beauty": "Record the bride's reaction at first mirror moment. A voice QR card captures the emotion that even the best photo cannot convey.",
    "wedding-florist": "Record the bride describing her bouquet or the meaning behind each flower. A voice QR card outlasts the blooms it celebrates.",
    "honeymoon": "Newlyweds record their first message as a married couple. A voice QR card from the honeymoon becomes a treasured anniversary tradition.",
    "funeral": "Preserve the deceased's voice, family eulogies, or farewell messages. A QR code on the memorial plaque lets loved ones hear those voices forever.",
    "ocean-scattering": "Record family words spoken during the ceremony. A voice QR card with GPS coordinates lets them return to the moment through sound.",
    "memorial-reef": "Document the placement ceremony with spoken tributes. A voice QR card accompanies the reef record, adding human voices to the ocean memorial.",
    "church": "Record baptism blessings, confirmation promises, or the pastor's words. A voice QR card adds living sound to sacred milestone records.",
    "temple": "Preserve dharma talks, chanting, or personal spiritual reflections. A voice QR card carries the teaching forward alongside the quartz record.",
    "heiau": "Record oral histories, genealogy chants, and cultural ceremonies. Voice QR preserves Hawaiian traditions in the spoken form they were meant to carry.",
    "military-memorial": "Preserve veterans' oral histories and family tributes. A voice QR card at Pearl Harbor or any memorial site adds personal testimony to the record.",
    "veterans": "Record veterans telling their service stories in their own voice. A QR card ensures these firsthand accounts survive for future generations.",
    "pet-memorial": "Preserve the sound of a beloved pet or the owner's spoken tribute. A voice QR on the memorial keeps the bond alive through sound.",
    "grief": "Record healing messages, letters to the departed, or memory sharing. Voice QR serves as a therapeutic tool in the grief counseling process.",
    "kona-coffee": "Record the farmer narrating the journey from cherry to cup. A voice QR tag on the bag lets customers hear the story behind every sip.",
    "macadamia": "Capture the farm tour guide's stories or the orchard history in voice. A QR card turns a farm visit into a permanent audio souvenir.",
    "pineapple": "Record the harvest story and tasting notes in the grower's voice. A QR tag on the crate delivers farm-to-table storytelling at home.",
    "vanilla": "Capture the farmer explaining the hand-pollination process. A voice QR tag on vanilla products adds artisanal narrative to every purchase.",
    "chocolate": "Record the chocolatier's story from cacao to bar. A QR tag lets customers hear the craft behind the chocolate they're tasting.",
    "distillery": "Capture the master distiller explaining the spirit's character. A voice QR on the bottle label lets every pour come with a personal story.",
    "brewery": "Record the brewmaster describing the hop profile and inspiration. A voice QR on the label turns craft beer into a personal conversation.",
    "winery": "Capture the vintner narrating terroir and vintage notes. A voice QR on the wine label adds a personal tasting guide to every bottle.",
    "honey": "Record the beekeeper's story about the hive and the flowers. A voice QR on the honey jar connects the sweetness to its natural origin.",
    "lavender": "Capture the farmer describing the harvest and distillation process. A voice QR tag adds sensory storytelling to lavender products.",
    "tropical-fruit": "Record the grower describing the variety and perfect ripeness. A voice QR sticker on fruit boxes delivers farm-fresh stories to kitchens.",
    "farmers-market": "Vendors record their story and growing philosophy. Voice QR tags at market stalls let customers take the farmer's voice home.",
    "hawaiian-jewelry": "Record the artisan explaining the cultural meaning of the design. A voice QR card in the jewelry box adds sacred context to each piece.",
    "lei": "Capture the lei maker sharing the tradition and flower significance. A voice QR card accompanies the lei, preserving aloha in spoken form.",
    "aloha-wear": "Record the designer's inspiration story. A voice QR tag sewn into the garment lets wearers hear the aloha spirit behind the print.",
    "ukulele": "Record the first song played on a new ukulele. A voice QR card in the case preserves the musical beginning forever.",
    "art-gallery": "Artists record their creative process and vision. A voice QR next to each piece turns gallery visits into intimate studio conversations.",
    "tattoo": "Record the meaning behind the tattoo in the client's own words. A voice QR card preserves the story that the ink tells silently.",
    "surfboard-shaper": "Capture the shaper explaining the board's design and rocker. A voice QR sticker inside the board carries the craft story into every wave.",
    "hawaiian-quilt": "Record the quilter explaining the pattern's Hawaiian meaning. A voice QR tag adds cultural depth that stitches alone cannot convey.",
    "koa-wood": "Record the woodworker narrating the tree's history and grain. A voice QR card with koa items connects the owner to the wood's origin story.",
    "shell-art": "Capture the artist describing where each shell was found. A voice QR card turns shell art into a piece with a spoken provenance.",
    "gift-shop": "Attach voice messages to gifts — the giver's voice plays when the QR is scanned. Every present becomes personally narrated.",
    "antique": "Record the dealer's provenance story for each piece. A voice QR card adds spoken history that written tags cannot capture.",
    "bookstore": "Feature author voice notes or staff recommendations as audio. A voice QR bookmark turns every purchase into a personally curated experience.",
    "spa": "Record a post-treatment reflection or therapist's wellness tip. A voice QR card extends the spa's calming presence beyond the visit.",
    "yoga": "Capture the instructor's guided meditation or closing intention. A voice QR card lets students replay the practice's peaceful energy at home.",
    "pilates": "Record the instructor's posture tips or milestone acknowledgment. A voice QR card continues the coaching between sessions.",
    "meditation": "Preserve a guided meditation or personal mantra in the teacher's voice. A QR card becomes a portable mindfulness practice.",
    "lomilomi": "Record the practitioner sharing the spiritual tradition behind the massage. A voice QR card carries Hawaiian healing wisdom beyond the session.",
    "hospital": "Record discharge messages, care instructions, or patient milestones. A voice QR card adds personal warmth to healthcare communication.",
    "clinic": "Record doctor's wellness advice or celebration of health milestones. A voice QR card makes medical visits more personal and memorable.",
    "dental": "Record congratulations for cavity-free checkups or kids' bravery awards. A voice QR card turns dental visits into positive, collectible memories.",
    "nursing": "Preserve residents' life stories and family voice messages. Voice QR plates in rooms keep loved ones' voices present every day.",
    "retirement": "Record life stories and messages for future generations. Voice QR becomes a legacy tool that preserves the wisdom of experience.",
    "rehab": "Record milestone achievements and encouragement from care teams. A voice QR card celebrates recovery progress with personal voices.",
    "mental-health": "Record affirmations, therapeutic breakthroughs, or self-compassion messages. Voice QR cards serve as tangible anchors for emotional healing.",
    "cultural-center": "Record oral histories, traditional songs, and community stories. Voice QR preserves living culture in the voices that carry it.",
    "university": "Capture commencement speeches, professor wisdom, or campus traditions in audio. Voice QR cards create lasting university memory keepsakes.",
    "language-school": "Record students' progress — first sentences, conversations, presentations. Voice QR cards track language learning milestones through actual speech.",
    "hula": "Capture the chants, the oli, and the kumu's teachings in voice. A QR card preserves hula tradition in its most authentic form — sound.",
    "ukulele-school": "Record students playing their first song. A voice QR graduation card lets them hear their own progress years later.",
    "cooking-class": "Capture the chef's secret tips and students' tasting reactions. A voice QR recipe card brings the cooking class home.",
    "museum": "Curators record exhibit stories in their own voice. Voice QR labels provide intimate, server-free audio guides that work even underground.",
    "aquarium": "Marine biologists record animal facts and conservation messages. Voice QR signs at tanks create engaging, offline audio experiences for visitors.",
    "zoo": "Zookeepers share animal stories and personalities in their own voice. Voice QR signs at enclosures create a personal, audio-guided visit.",
    "botanical-garden": "Botanists record plant stories and seasonal highlights. Voice QR garden markers provide intimate audio tours without any app download.",
    "real-estate": "Record the homeowner's memories or the agent's neighborhood story. A voice QR in property materials adds personal narrative to listings.",
    "law-firm": "Record client testimonials or attorney introductions. Voice QR on business cards or brochures adds a personal dimension to legal services.",
    "insurance": "Record personal messages for beneficiaries. A voice QR card with the policy ensures loved ones hear your voice when it matters most.",
    "bank": "Record milestone messages at account openings or retirement planning. A voice QR card adds personal meaning to financial milestones.",
    "car-rental": "Record driving highlights or island exploration tips. A voice QR card in the glovebox turns a rental into a narrated island adventure.",
    "limousine": "Record celebration messages during the ride. A voice QR card from the evening preserves the luxury experience in the guests' own voices.",
    "concierge": "Record personalized recommendations in the concierge's voice. A voice QR card gives guests a portable, personal audio guide to the island.",
    "photo-studio": "Record the story behind the portrait session. A voice QR card paired with photos creates a multi-sensory memory package.",
    "event-planner": "Capture keynote highlights or guest messages at events. Voice QR cards serve as audio souvenirs that replay the event's best moments.",
    "moving": "Record goodbye messages to the old home or first impressions of the new one. A voice QR card marks life's biggest transitions with personal voices.",
    "fine-dining": "Record the chef's tasting menu narration or wine pairing notes. A voice QR menu card elevates dining into a multi-sensory experience.",
    "poke": "Record the fisherman's catch story or the chef's flavor philosophy. A voice QR sign at the counter adds local authenticity to every bowl.",
    "shave-ice": "Capture the story of the shop, the syrup flavors, and the family recipe. A voice QR card turns a treat into a sweet, shareable memory.",
    "farm-to-table": "Record the farmer describing today's harvest. A voice QR on the table lets diners hear the origin story of what they're eating.",
    "bakery": "Record the baker's early-morning story or the recipe's heritage. A voice QR tag on bread bags delivers warmth beyond the oven.",
}
